name: linkify
authors:
- Nikolaus Graf <nik@blossom.io>
- Peter Kofler <peter.kofler@code-cop.org>
version: 1.0.0
homepage: https://github.com/blossom/linkify-dart
description: Takes a string of plain text and linkifies URLs and email addresses. Dart port of Google closure-library's String.linkify
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
